Code review - (g-golf support struct)
* g-golf/support/struct.scm: Adding a missing
  #:duplicates (merge-generics replace warn-override-core warn last)
  to the module definition.

  Also, temporarily commenting the g-export for the !gtype-id accessor,
  it surprisingly creates a problem, exactly where I didn't figure out
  yet, but that manifest itself in make check, test-closure-gobject,
  which I can then reproduce manually:

    ,use (g-golf)
    (gi-import "Clutter")
    (make <clutter-actor>)
    $2 = #<<clutter-actor> 56523e432480>
    scheme@(guile-user)> (!gtype-id $2)
    ERROR: In procedure scm-error:
    ...

  But there is something else I want to fix before to deal with this
  bug, related to the 'yet to be commited' g-io-add-watch-fd, which
  needs the GIOChannel (semi-opaque) struct to be imported, then I'll
  get back to this.